import Head from "next/head";

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Contact Us Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      contact us
    </div>
  );
}
