import Head from "next/head";
import styles from "../styles/Home.module.css";
import { CgMenuRightAlt, CgClose } from "react-icons/cg";
import { useState } from "react";
import Link from "next/link";
import { Navigate, useNavigate } from "react-router-dom";
import Navbar from "../components/Navbar";

export default function Home() {
  const [active, setActive] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.navStyle}>
        <div className="logo">
          <h1>Logo </h1>{" "}
        </div>
        {/* <div className={(styles.searchField, styles.activate)}>
          <input
            type="text"
            className={styles.inputField}
            name=""
            id=""
            placeholder="Search for Events"
            style={{
              padding: "9px 15px",
              borderRadius: "10px",
              border: "1px solid grey",
            }}
          />
        </div> */}
        {!active && (
          <nav className={active ? "web-menu__inactive" : "web-menu__active"}>
            <ul>
              <Link href="/">
                <li>
                  <a className="">Home</a>
                </li>
              </Link>
              <Link href="/about">
                <li>
                  <a className="">About</a>
                </li>
              </Link>
              <Link href="/contact">
                <li>
                  <a>Contact Us</a>
                </li>
              </Link>
              <Link href="/sign-in">
                <li>Sign In</li>
              </Link>
              <Link href="/sign-up">
                <li>Sign Up</li>
              </Link>
            </ul>
          </nav>
        )}

        <div className="mob-menu mob-menu__active">
          {" "}
          {active ? (
            <CgMenuRightAlt size={40} onClick={() => setActive(!active)} />
          ) : (
            <CgClose size={40} onClick={() => setActive(!active)} />
          )}
        </div>
      </header>

      <main id="main" className={styles.main}>
        <h1 className={styles.name}>
          Getting you right on track to complete your CME requirements
        </h1>
      </main>
    </div>
  );
}
